### PR TITLE
2 bits of opcode and 8 bits of address (10bit total)

### PR DESCRIPTION
**Pull request by egzumer**
this is related to https://github.com/0xJoey/Arduino_93C46/issues/4

I used this library almost one year ago to read tachometer eeprom, this is what I changed to fix the issue. I don't remember now what to look for regarding "other functions".

### CODE REVIEW

**Comment by Devilscave** [comment]
I have to ask now: What's right now? In the whole Issues and forum here are different solutions, how can I evaluate whether my read-out data is correct?
Before this change, my output was:

`CHIP 1 Speichertest: 0123456789 abcdefghijklmnop ABCDEFGHIJKLMNO`
`	00	01	02	03	04	05	06	07	08	09	0A	0B	0C	0D	0E	0F`
`0	43	48	49	50	20	31	20	53	70	65	69	63	68	65	72	74`
`10	65	73	74	3A	20	30	31	32	33	34	35	36	37	38	39	20`
`20	61	62	63	64	65	66	67	68	69	6A	6B	6C	6D	6E	6F	70`
`30	20	41	42	43	44	45	46	47	48	49	4A	4B	4C	4D	4E	4F`

after this change:

`    $$$$@@@@⸮⸮⸮⸮⸮⸮⸮Ȁ⸮⸮⸮LLLL⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮`
`	00	01	02	03	04	05	06	07	08	09	0A	0B	0C	0D	0E	0F`
`0	10C	10C	10C	10C	120	10C	120	10C	124	120	124	120	140	120	140	120`
`10	80	124	80	124	C4	124	C4	124	80	140	80	140	14C	140	14C	140`
`20	1C0	80	1C0	80	194	80	194	80	1A4	C8	1A4	C8	78C	C8	5AC	C8`
`30	23A	80	19	80	A3	80	3302	80	1A02	14C	DF08	14C	4000	14C	4000	14C`

And then I read in Issues # 3 that the output is only displayed half and have made this change too. I get other issues again:

`CHIP 2 Speichertest: 0123456789 abcdefghijklmnop ABCDEFGHIJKLMNO`
`       00	01	02	03	04	05	06	07	08	09	0A	0B	0C	0D	0E	0F`
`0	43	43	49	48	20	49	20	50	70	20	69	32	68	20	72	53`
`10	65	70	74	65	20	69	31	63	33	68	35	65	37	72	39	74`
`20	61	65	63	73	65	74	67	3A	69	20	6B	30	76D	31	5AC	32`
`30	206	33	19	34	A3	35	3302	36	1A02	37	DF08	38	4000	39	4000	20`

In the first and in the third edition, I can at least read the text that was written by me in the chip. At the second no longer. Will he be written wrong there?

**Comment by egzumer** [comment]
I read the eeprom for PIN code which was supposed to be written at a specific location and repeated twice. It didn't look like that with the original code. After the change all worked well and the PIN worked too, so I can assume I fixed the issue for the function that I changed.

The write function looks like it has the same broken part of the code so you shouldn't expect it to write correct data at correct memory cells. If you modify the write function accordingly you should be able to read same thing that you write.

**Comment by Devilscave** [comment]
Thank you for your quick response.
As you can see on the three examples, in the first line, I can read the text that is saved as the value.
The second example with your change is no longer the case.
But in the third example, you can see that you can read the text and the code looks at the beginning as in Example 1 and towards the end as in Example 2.

**Comment by egzumer** [comment]
I would say that what you see in example 2 is what is actually in the eeprom memory. I only fixed the read function as I only needed that one so you will get different read result from the write. I only created this pull request to help the original creator, this isn't complete fix. You have to fix the write function.

Also I don't know what is the content that you wrote to the memory, and I don't know how to read your output.

**Comment by Devilscave** [comment]
Ok, all right, thank you very much for your effort.

**Comment by 0xJoey** [comment]
I really don't check this repository all too often, my apologies for that! Merged it, thanks for the help :)

**Pull request merged**
